-- Projects table
-- Source of truth: BACKEND_API.md (Project schema)
-- One-time migration; can be removed after running in each environment.

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  category text not null,
  description text not null,
  full_description text not null,
  image text not null,
  media jsonb not null default '[]'::jsonb,
  features jsonb not null default '[]'::jsonb,
  duration text not null,
  tech jsonb not null default '[]'::jsonb,
  featured boolean not null default false,
  results jsonb not null default '[]'::jsonb,
  client text,
  live_link text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.projects is 'Portfolio projects. Schema source: BACKEND_API.md';
comment on column public.projects.media is 'Array of { "type": "image"|"video", "url": "string" }';
comment on column public.projects.features is 'Array of feature strings';
comment on column public.projects.tech is 'Array of technology strings';
comment on column public.projects.results is 'Array of outcome/result strings';

-- Public read; write can be restricted later with auth
alter table public.projects enable row level security;

create policy "Allow public read on projects"
  on public.projects for select
  using (true);

create index if not exists projects_slug_idx on public.projects (slug);
create index if not exists projects_featured_idx on public.projects (featured) where featured = true;
