-- Profiles: one row per auth user. role = 'admin' | 'team_member'.
-- Team members have team_slug (e.g. 'uzair-yasin') and profile_data (editable).
-- Source: auth.users; profiles define app role and team profile content.

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'team_member')),
  team_slug text,
  profile_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.profiles is 'App user profiles: role (admin/team_member) and editable team profile data.';
comment on column public.profiles.profile_data is 'Team member editable fields: name, role, description, fullDescription, image, skills[], certificates[], bulletPoints[], cvLink, socials{}';

alter table public.profiles enable row level security;

create policy "Users can read own profile"
  on public.profiles for select
  using (auth.uid() = user_id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- No insert policy for anon/authenticated; only service role (e.g. seed script) can insert.

-- Helper for RLS: current user's role (null if no profile)
create or replace function public.get_my_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where user_id = auth.uid() limit 1;
$$;

-- Projects: add owner (team member who created it). Null = legacy/no owner; admin can edit any.
alter table public.projects
  add column if not exists owner_id uuid references auth.users(id) on delete set null;

comment on column public.projects.owner_id is 'User who owns the project. Null = no owner; admin can edit all.';

-- Drop old write policies so we can replace with role-aware ones
drop policy if exists "Allow anon insert on projects" on public.projects;
drop policy if exists "Allow anon update on projects" on public.projects;
drop policy if exists "Allow anon delete on projects" on public.projects;

-- Projects: team member can only see/edit/delete own; admin can do all; anyone can read (public)
create policy "Allow insert own project or admin"
  on public.projects for insert
  with check (
    auth.uid() is not null
    and (public.get_my_role() = 'admin' or (public.get_my_role() = 'team_member' and owner_id = auth.uid()))
  );

create policy "Allow update own or admin"
  on public.projects for update
  using (
    public.get_my_role() = 'admin'
    or owner_id = auth.uid()
  )
  with check (
    public.get_my_role() = 'admin'
    or owner_id = auth.uid()
  );

create policy "Allow delete own or admin"
  on public.projects for delete
  using (
    public.get_my_role() = 'admin'
    or owner_id = auth.uid()
  );

-- Team member can insert only with owner_id = self; admin can insert with any owner_id
create policy "Allow insert project"
  on public.projects for insert
  with check (
    auth.uid() is not null
    and (
      public.get_my_role() = 'admin'
      or (public.get_my_role() = 'team_member' and owner_id = auth.uid())
    )
  );

create index if not exists projects_owner_id_idx on public.projects (owner_id);
create unique index if not exists profiles_user_id_idx on public.profiles (user_id);
