-- n8n workflows table for admin-managed workflow list.
-- Source of truth for N8nWorkflows section on landing.

create table if not exists public.n8n_workflows (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  nodes int not null default 0,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.n8n_workflows enable row level security;

create policy "Allow public read on n8n_workflows"
  on public.n8n_workflows for select
  using (true);

create policy "Allow anon insert on n8n_workflows"
  on public.n8n_workflows for insert
  with check (true);

create policy "Allow anon update on n8n_workflows"
  on public.n8n_workflows for update
  using (true);

create policy "Allow anon delete on n8n_workflows"
  on public.n8n_workflows for delete
  using (true);

create index if not exists n8n_workflows_sort_order_idx on public.n8n_workflows (sort_order);
